### ISSUE TITLE
Update NeatoBurritoLibrary to latest

### ISSUE THREAD

**Issue by KairuByte** [Popat0/Discord-GSI#7]
Current repo has v0.9.28 while current version is v0.9.29.

**Comment by SkedgyEdgy** [comment]
may i ask how i would do this myself as it doesn't seem like this is maintained at all anymore

**Comment by Popat0** [comment]
It's not that this isn't maintained as much as it is about the Neato Burrito Library having been abandoned.

You can find an alternative update of this plugin that does not rely on that (now dead) library here : https://github.com/AAGaming00/Aurora-GSI-Powercord/blob/dev/AuroraGSI.plugin.js
It will be rehosted here once it's stable and has some code improvements.

**Comment by SkedgyEdgy** [comment]
ohhhhhhh, okay. sorry for misunderstanding ^^

**Comment by Popat0** [comment]
Don't worry about it, I should probably have made that more obvious and communicated here too instead of just on discord. Anywho, closing as this will get resolved when AAGaming finishes his version.
